# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate json5

Name:           rust-%{crate}
Version:        0.2.5
Release:        1%{?dist}
Summary:        Rust JSON5 serializer and deserializer which speaks Serde

# Upstream license specification: ISC
License:        ISC
URL:            https://crates.io/crates/json5
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust JSON5 serializer and deserializer which speaks Serde.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Feb 13 12:24:59 MSK 2020 Nikita Kretov <nkretov@croc.ru> - 0.2.5-1
- Initial package
