# Generated by rust2rpm 13
%bcond_without check

%global crate shadowsocks-rust

Name:           rust-%{crate}
Version:        1.8.8
Release:        1%{?dist}
Summary:        Shadowsocks is a fast tunnel proxy that helps you bypass firewalls

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/shadowsocks-rust
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Shadowsocks is a fast tunnel proxy that helps you bypass firewalls.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%{_bindir}/ssredir
%{_bindir}/ssurl
%{_bindir}/sslocal
%{_bindir}/ssserver
%{_bindir}/sstunnel
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+aes-cfb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-cfb-devel %{_description}

This package contains library source intended for building other packages
which use "aes-cfb" feature of "%{crate}" crate.

%files       -n %{name}+aes-cfb-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+aes-ctr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-ctr-devel %{_description}

This package contains library source intended for building other packages
which use "aes-ctr" feature of "%{crate}" crate.

%files       -n %{name}+aes-ctr-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+camellia-cfb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+camellia-cfb-devel %{_description}

This package contains library source intended for building other packages
which use "camellia-cfb" feature of "%{crate}" crate.

%files       -n %{name}+camellia-cfb-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libsodium-sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsodium-sys-devel %{_description}

This package contains library source intended for building other packages
which use "libsodium-sys" feature of "%{crate}" crate.

%files       -n %{name}+libsodium-sys-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+miscreant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+miscreant-devel %{_description}

This package contains library source intended for building other packages
which use "miscreant" feature of "%{crate}" crate.

%files       -n %{name}+miscreant-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages
which use "openssl" feature of "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+openssl-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-vendored-devel %{_description}

This package contains library source intended for building other packages
which use "openssl-vendored" feature of "%{crate}" crate.

%files       -n %{name}+openssl-vendored-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rc4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rc4-devel %{_description}

This package contains library source intended for building other packages
which use "rc4" feature of "%{crate}" crate.

%files       -n %{name}+rc4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+redir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+redir-devel %{_description}

This package contains library source intended for building other packages
which use "redir" feature of "%{crate}" crate.

%files       -n %{name}+redir-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+single-threaded-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+single-threaded-devel %{_description}

This package contains library source intended for building other packages
which use "single-threaded" feature of "%{crate}" crate.

%files       -n %{name}+single-threaded-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sodium-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sodium-devel %{_description}

This package contains library source intended for building other packages
which use "sodium" feature of "%{crate}" crate.

%files       -n %{name}+sodium-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust-dns-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-resolver-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns-resolver" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-resolver-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Feb 10 23:10:26 MSK 2020 Nikita Kretov <nkretov@croc.ru> - 1.8.8-1
- Initial package
