# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate tokio-executor

Name:           rust-%{crate}
Version:        0.2.0~alpha.6
Release:        1%{?dist}
Summary:        Future execution primitives

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/tokio-executor
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Future execution primitives.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+blocking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+blocking-devel %{_description}

This package contains library source intended for building other packages
which use "blocking" feature of "%{crate}" crate.

%files       -n %{name}+blocking-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+crossbeam-channel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossbeam-channel-devel %{_description}

This package contains library source intended for building other packages
which use "crossbeam-channel" feature of "%{crate}" crate.

%files       -n %{name}+crossbeam-channel-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+crossbeam-deque-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossbeam-deque-devel %{_description}

This package contains library source intended for building other packages
which use "crossbeam-deque" feature of "%{crate}" crate.

%files       -n %{name}+crossbeam-deque-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+crossbeam-queue-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossbeam-queue-devel %{_description}

This package contains library source intended for building other packages
which use "crossbeam-queue" feature of "%{crate}" crate.

%files       -n %{name}+crossbeam-queue-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+crossbeam-utils-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossbeam-utils-devel %{_description}

This package contains library source intended for building other packages
which use "crossbeam-utils" feature of "%{crate}" crate.

%files       -n %{name}+crossbeam-utils-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+current-thread-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+current-thread-devel %{_description}

This package contains library source intended for building other packages
which use "current-thread" feature of "%{crate}" crate.

%files       -n %{name}+current-thread-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-core-preview-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-preview-devel %{_description}

This package contains library source intended for building other packages
which use "futures-core-preview" feature of "%{crate}" crate.

%files       -n %{name}+futures-core-preview-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages
which use "lazy_static" feature of "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+num_cpus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num_cpus-devel %{_description}

This package contains library source intended for building other packages
which use "num_cpus" feature of "%{crate}" crate.

%files       -n %{name}+num_cpus-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+slab-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+slab-devel %{_description}

This package contains library source intended for building other packages
which use "slab" feature of "%{crate}" crate.

%files       -n %{name}+slab-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+threadpool-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+threadpool-devel %{_description}

This package contains library source intended for building other packages
which use "threadpool" feature of "%{crate}" crate.

%files       -n %{name}+threadpool-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-sync-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-sync-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-sync" feature of "%{crate}" crate.

%files       -n %{name}+tokio-sync-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages
which use "tracing" feature of "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Feb 13 11:25:35 MSK 2020 Nikita Kretov <nkretov@croc.ru> - 0.2.0~alpha.6-1
- Initial package
