# Generated by rust2rpm 13
%bcond_without check

%global crate shadowsocks-rust

Name:           rust-%{crate}
Version:        1.7.0
Release:        1%{?dist}
Summary:        Shadowsocks is a fast tunnel proxy that helps you bypass firewalls

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/shadowsocks-rust
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Shadowsocks is a fast tunnel proxy that helps you bypass firewalls.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%{_bindir}/sslocal
%{_bindir}/ssserver
%{_bindir}/ssurl
%{_bindir}/ssdns
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libsodium-ffi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsodium-ffi-devel %{_description}

This package contains library source intended for building other packages
which use "libsodium-ffi" feature of "%{crate}" crate.

%files       -n %{name}+libsodium-ffi-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+miscreant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+miscreant-devel %{_description}

This package contains library source intended for building other packages
which use "miscreant" feature of "%{crate}" crate.

%files       -n %{name}+miscreant-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rc4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rc4-devel %{_description}

This package contains library source intended for building other packages
which use "rc4" feature of "%{crate}" crate.

%files       -n %{name}+rc4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sodium-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sodium-devel %{_description}

This package contains library source intended for building other packages
which use "sodium" feature of "%{crate}" crate.

%files       -n %{name}+sodium-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Feb 13 12:34:30 MSK 2020 Nikita Kretov <nkretov@croc.ru> - 1.7.0-1
- Initial package
